server:
  port: 8090
spring:
  data:
    mongodb:
      username: soufiane
      password: soufiane
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin